# Dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
# RATING_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
    # inter: [user_id, item_id, label]
    item: [item_id,book_title,book_author,publication_year,publisher]
    user: [user_id,location,age]
user_inter_num_interval: [13,100]

# Training and evaluation config
seed: 1128
epochs: 50
train_batch_size: 32
valid_metric: rmse

# Evaluate config
eval_args:
    group_by: task
    order: RO
    split: {'RS': [0.8,0.1,0.1]}
    mode : labeled

# Meta learning config
meta_args:
    support_num: none
    query_num: 10

# MeLU Parameters
embedding_size: 32
mlp_hidden_size: [64,64]
melu_args:
    local_lr: 0.000005
    lr: 0.00005

# Metrics
# metrics: ['precision','recall','hit','ndcg']
metrics: ['rmse']
metric_decimal_place: 4
topk: 5